### ISSUE TITLE
custom error pages on cdn-route

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1091]
in order to prevent hand-made changes on s3-buckets, we should add the ability to set custom error pages in the cdn broker.

Right now, we have no support for custom error pages on the cdn broker, and we're adding custom error pages to S3 bucket websites for federalist

**Comment by bengerman13** [comment]
@jontours or @eddietejeda if either of you have context on why we're setting this on S3 buckets for Federalist rather than on the CloudFront distribution, I'd be interested to hear it.

**Comment by bengerman13** [comment]
relates to 18F/cg-product#999

**Comment by eddietejeda** [comment]
@amirbey ?

**Comment by amirbey** [comment]
A self-serve functionality to set custom error pages on cdn-routes would be very helpful for us and our clients. Very helpful!  I'm assuming this would be an attribute for the cdn-route.

I'm assuming this question arises from yesterday's cg-support request to set the routing for a cloudront url  with an S3 origin where the error routing was already set at the bucket level.  This is the first and only instance thus far where we've set the routing at the bucket level.  We experimented with this because this was the first instance on which a client needed custom error routing (for React routing) and they were on their own dedicated bucket. And, did not require all the processes involved to issue a cloudfront distro enabling the client to begin development ASAP. Ultimately, we've concluded we still need the error routing to occur in the cloudfront distro.

**Comment by eddietejeda** [comment]
Would it make sense of default to all buckets to support customer 404?

**Comment by amirbey** [comment]
we could support customer 404 routing at the bucket level. however, for federalist users using React Routing ... we would still need to request custom 404 routing for cloudfront distros to enable users to have dev and production environments b/c each environment has its own cloudfront url.

**Comment by bengerman13** [comment]
To be clear - my suggestion here is to pull the setting off of the bucket and onto the CloudFront distribution, but it would then be available to whoever creates the CloudFront distribution at the time of creation and/or update

**Comment by amirbey** [comment]
I agree @bengerman13 .  That is our desired approach as well.

**Comment by hillaryj** [comment]
As a clarification, there's at least one case where we set the error page on the s3 bucket, but the recent request got clarified to be set as an error page in CloudFront instead. It would definitely be good to let Federalist sites set those themselves or default to some behavior.

**Comment by bengerman13** [comment]
@mxplusb I'm leaving this open so we don't forget about it, but it seems worthwhile to think about when we get to the CDN on the new broker.

**Comment by mxplusb** [comment]
@bengerman13 this came up as part of 18f/cg-private#98.
