### ISSUE TITLE
adapt oauth2-proxy-boshrelease to work with new oauth2_proxy fork

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1142]
In order to deliver the updated oauth2_proxy fork, we'll need to adapt the oauth2-proxy-boshrelease.

Acceptance criteria:
- [ ] When we build oauth2-proxy-boshrelease, it incorporates the new oauth2_proxy fork

**Comment by hillaryj** [comment]
Priority in the next few sprints, blocked by the fork-switch issue.

**Comment by mxplusb** [comment]
So I don't think we actually need to do this. It turns out our ELBs support OIDC configurations on listeners, you can see it working on [doomsday's listener](https://github.com/18F/cg-provision/blob/master/terraform/modules/monitoring/elb.tf#L50). I think that's a much easier and more sustainable path to go down as we are no longer responsible for owning a proxy or piece of software, we can integrate with AWS and then we're worry free.
