### ISSUE TITLE
Production-grade Stratos

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-product#905]

**Comment by mogul** [comment]
In order to promote Stratos from beta to production status, we want Stratos deployed in a production-worthy state.

## Acceptance Criteria
* [ ] things load fast for admins
--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] Deploy with a real DB instead of SQLite

**Comment by mxplusb** [comment]
There is a bug in Stratos that I found today that disallows us from using it with the AWS broker. I was testing it in staging while trying to fix the pipeline. [Details](https://cloudfoundry.slack.com/archives/C80EP4Y57/p1578353267007000)

**Comment by mogul** [comment]
You could write a start-cmd that just renames that part of the envvar...

**Comment by mxplusb** [comment]
No, this is an actual bug in Stratos. They should fail to see a required field in the JSON structure and then default to using the URI, that's the explicit logic in Stratos. I talked with @richard-cox about it and the problem is it's thinking the `hostname` field exists (in our broker it does not) and not falling back to the URI (which our broker has and it expects). Because this is an actual bug and not a nuanced difference, it should get fixed properly.

**Comment by mogul** [comment]
I agree it's a bug! I was just suggesting that you could work around it for now.

**Comment by mxplusb** [comment]
Fix was implemented and will be formally released soon: https://github.com/cloudfoundry/stratos/pull/4084

**Comment by hillaryj** [comment]
They released a RC yesterday (2.7.0 Release Candidate 2) that includes this fix, hopefully it'll make it through and we'll get this soon.
